import type { LiveToolMoment, LiveToolTemplate } from "./types";

const now = "system";

export const LIVE_TOOL_MOMENTS: LiveToolMoment[] = [
  "pre-service",
  "live-service",
  "emergency",
  "post-service",
];

export const DEFAULT_LIVE_TOOL_TEMPLATES: LiveToolTemplate[] = [
  {
    id: "countdown",
    moment: "pre-service",
    kind: "countdown",
    label: "Start Countdown",
    description: "Show a simple service countdown screen.",
    icon: "timer",
    title: "Service starts in",
    subtitle: "Welcome to church",
    durationSeconds: 300,
    backgroundColor: "#101820",
    sortOrder: 10,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "welcome-loop",
    moment: "pre-service",
    kind: "media-loop",
    label: "Welcome Loop",
    description: "Play a welcome image or video loop.",
    icon: "waving_hand",
    title: "Welcome",
    subtitle: "We are glad you are here",
    backgroundColor: "#111827",
    sortOrder: 20,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "announcements-loop",
    moment: "pre-service",
    kind: "media-loop",
    label: "Announcements Loop",
    description: "Play announcement media before service.",
    icon: "campaign",
    title: "Announcements",
    subtitle: "Stay connected with what is happening",
    backgroundColor: "#172554",
    sortOrder: 30,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "holding-screen",
    moment: "pre-service",
    kind: "fullscreen",
    label: "Holding Screen",
    description: "Show a simple waiting screen.",
    icon: "desktop_windows",
    title: "Service Starting Soon",
    subtitle: "Please stay with us",
    backgroundColor: "#0f172a",
    sortOrder: 40,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "speaker-lower-third",
    moment: "live-service",
    kind: "lower-third",
    label: "Speaker Lower Third",
    description: "Display the speaker name and topic.",
    icon: "badge",
    title: "Speaker Name",
    subtitle: "Sermon Topic",
    backgroundColor: "#111827",
    sortOrder: 110,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "quick-text",
    moment: "live-service",
    kind: "fullscreen",
    label: "Quick Text",
    description: "Send a fast full-screen text card.",
    icon: "text_fields",
    title: "Service Notice",
    subtitle: "Please follow the instruction on screen",
    backgroundColor: "#1f2937",
    sortOrder: 120,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "background-switch",
    moment: "live-service",
    kind: "media-loop",
    label: "Background Switch",
    description: "Switch to a prepared background media item.",
    icon: "wallpaper",
    title: "Background Media",
    subtitle: "Select media in Edit",
    backgroundColor: "#0f172a",
    sortOrder: 130,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "prepared-scene",
    moment: "live-service",
    kind: "scene",
    label: "Prepared Scene",
    description: "Load a configured OBS scene without hunting inside OBS.",
    icon: "slideshow",
    title: "Prepared Scene",
    subtitle: "Choose an OBS scene in Edit",
    backgroundColor: "#111827",
    sortOrder: 140,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "technical-difficulties",
    moment: "emergency",
    kind: "fullscreen",
    label: "Technical Difficulties",
    description: "Show a safe technical-issue message.",
    icon: "report_problem",
    title: "Technical Difficulties",
    subtitle: "Please stay with us.",
    body: "We are working to restore the stream.",
    backgroundColor: "#2f1d1d",
    sortOrder: 210,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "audio-issue",
    moment: "emergency",
    kind: "fullscreen",
    label: "Audio Issue",
    description: "Show an audio issue message.",
    icon: "volume_off",
    title: "Audio Issue",
    subtitle: "Please wait while we fix the sound.",
    backgroundColor: "#2a2414",
    sortOrder: 220,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "stream-paused",
    moment: "emergency",
    kind: "fullscreen",
    label: "Stream Paused",
    description: "Show a be-right-back style screen.",
    icon: "pause_circle",
    title: "We will be back shortly",
    subtitle: "Thank you for your patience.",
    backgroundColor: "#111827",
    sortOrder: 230,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "hide-overlays",
    moment: "emergency",
    kind: "safety-action",
    label: "Hide Overlays",
    description: "Hide OCS overlays from the selected output.",
    icon: "visibility_off",
    title: "Hide Overlays",
    action: "hide-overlays",
    backgroundColor: "#111827",
    sortOrder: 240,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "safe-scene",
    moment: "emergency",
    kind: "safety-action",
    label: "Safe Scene",
    description: "Switch to a configured safe OBS scene.",
    icon: "security",
    title: "Safe Scene",
    subtitle: "Choose an OBS scene in Edit",
    action: "safe-scene",
    backgroundColor: "#111827",
    sortOrder: 250,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "mute-mic",
    moment: "emergency",
    kind: "safety-action",
    label: "Mute Mic",
    description: "Mute a configured OBS audio source.",
    icon: "mic_off",
    title: "Mute Mic",
    subtitle: "Choose an OBS audio source in Edit",
    action: "mute-mic",
    backgroundColor: "#111827",
    sortOrder: 260,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "end-screen",
    moment: "post-service",
    kind: "fullscreen",
    label: "End Screen",
    description: "Show the final service screen.",
    icon: "flag",
    title: "Thanks for joining us",
    subtitle: "Have a blessed week.",
    backgroundColor: "#102018",
    sortOrder: 310,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "giving-info",
    moment: "post-service",
    kind: "fullscreen",
    label: "Giving Info",
    description: "Display giving or banking details.",
    icon: "volunteer_activism",
    title: "Giving",
    subtitle: "Thank you for your generosity.",
    body: "Add your giving details in Edit.",
    backgroundColor: "#13251f",
    sortOrder: 320,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "thank-you",
    moment: "post-service",
    kind: "fullscreen",
    label: "Thank You Screen",
    description: "Show a warm thank-you message.",
    icon: "favorite",
    title: "Thank you for worshipping with us",
    subtitle: "See you next service.",
    backgroundColor: "#1e293b",
    sortOrder: 330,
    isSystem: true,
    updatedAt: now,
  },
  {
    id: "outro-loop",
    moment: "post-service",
    kind: "media-loop",
    label: "Outro Loop",
    description: "Play an outro image or video loop.",
    icon: "subscriptions",
    title: "Outro Loop",
    subtitle: "Select media in Edit",
    backgroundColor: "#111827",
    sortOrder: 340,
    isSystem: true,
    updatedAt: now,
  },
];

export function getDefaultLiveTool(id: string): LiveToolTemplate | undefined {
  return DEFAULT_LIVE_TOOL_TEMPLATES.find((template) => template.id === id);
}
